# Generated by Django 3.2 on 2021-05-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0003_mycontest_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontest',
            name='contestLink',
            field=models.URLField(default=False),
        ),
        migrations.AlterField(
            model_name='mycontest',
            name='platform',
            field=models.CharField(choices=[('Codeforces', 'Codeforces'), ('Codechef', 'Codechef'), ('AtCoder', 'Atcoder')], default='Codeforces', max_length=20),
        ),
    ]
